# Generated by Django 3.0.6 on 2020-05-20 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_apis', '0007_userinfo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='communication',
            name='user',
        ),
        migrations.RemoveField(
            model_name='hobby',
            name='users',
        ),
        migrations.RemoveField(
            model_name='profileimage',
            name='user',
        ),
        migrations.RemoveField(
            model_name='projects',
            name='users',
        ),
        migrations.RemoveField(
            model_name='skills',
            name='users',
        ),
        migrations.RemoveField(
            model_name='userinfo',
            name='user',
        ),
        migrations.DeleteModel(
            name='achievements',
        ),
        migrations.DeleteModel(
            name='chat',
        ),
        migrations.DeleteModel(
            name='communication',
        ),
        migrations.DeleteModel(
            name='hobby',
        ),
        migrations.DeleteModel(
            name='profileimage',
        ),
        migrations.DeleteModel(
            name='projects',
        ),
        migrations.DeleteModel(
            name='skills',
        ),
        migrations.DeleteModel(
            name='userinfo',
        ),
    ]
