# Generated by Django 3.0.6 on 2020-05-28 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_apis', '0012_auto_20200526_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievements',
            name='description',
            field=models.CharField(default='SSAdsadasdsaas', max_length=200),
            preserve_default=False,
        ),
    ]
