# Generated by Django 3.0.3 on 2020-05-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_apis', '0013_achievements_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hobby',
            name='hobby_image_url',
            field=models.TextField(),
        ),
    ]
