# Generated by Django 3.0.6 on 2020-06-01 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_apis', '0014_badge'),
        ('rest_apis', '0014_auto_20200529_0320'),
    ]

    operations = [
    ]
