# Generated by Django 3.0.6 on 2020-06-05 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_apis', '0016_auto_20200605_1013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hobby',
            name='hobby_image_url',
        ),
    ]
