# Generated by Django 3.0.6 on 2020-06-05 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_apis', '0018_auto_20200605_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill_names',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='projects',
            name='skills',
            field=models.ManyToManyField(to='rest_apis.Skill_names'),
        ),
    ]
