# Generated by Django 3.0.6 on 2020-06-15 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_apis', '0020_auto_20200615_1610'),
    ]

    operations = [
        migrations.CreateModel(
            name='Industries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='languages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='userinfo',
            name='ContactNo',
            field=models.BigIntegerField(default=9131608791),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='Gender',
            field=models.TextField(default='male'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='Total_Experience',
            field=models.TextField(default='zero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(default='sanskarj@iitbhilai.ac.in', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='employeeid',
            field=models.TextField(default='123@thoucentric'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='joiningdate',
            field=models.TextField(default='2-3-2020'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='summary',
            field=models.TextField(default='this is my summary'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userinfo',
            name='industries',
            field=models.ManyToManyField(to='rest_apis.Industries'),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='languages',
            field=models.ManyToManyField(to='rest_apis.languages'),
        ),
    ]
