# Generated by Django 3.0.3 on 2020-06-10 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_apis', '0020_auto_20200608_0305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievements',
            name='date',
            field=models.TextField(),
        ),
    ]
