# Generated by Django 3.0.6 on 2020-06-15 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_apis', '0021_auto_20200615_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='projects',
            name='Industry_of_the_client',
            field=models.TextField(default='Software'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='Role',
            field=models.TextField(default='programmer'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='case_study_submitted',
            field=models.TextField(default='Yes'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='client_location',
            field=models.TextField(default='Mumbai'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='client_name',
            field=models.TextField(default='Sanskar'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='location_of_project_exceution',
            field=models.TextField(default='Delhi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='team_size',
            field=models.BigIntegerField(default=12),
            preserve_default=False,
        ),
    ]
