# Generated by Django 3.0.6 on 2020-06-15 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rest_apis', '0022_auto_20200615_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='location_of_project_exceution',
            new_name='location_of_project_execution',
        ),
    ]
