# Generated by Django 3.0.6 on 2020-06-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_apis', '0023_auto_20200615_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projects',
            name='team_size',
            field=models.TextField(),
        ),
    ]
