# Generated by Django 3.0.6 on 2020-06-18 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_apis', '0028_remove_projects_case_study_submitted'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='status',
            field=models.TextField(default='part time'),
            preserve_default=False,
        ),
    ]
