# Generated by Django 3.0.6 on 2020-06-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rest_apis', '0030_blog_blog_site'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projects',
            old_name='description',
            new_name='project_description',
        ),
        migrations.AddField(
            model_name='projects',
            name='benefits',
            field=models.TextField(default='no description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='multi_vendor',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='project_details',
            field=models.TextField(default='pro'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projects',
            name='proposed_solution',
            field=models.TextField(default='proposed'),
            preserve_default=False,
        ),
    ]
